---
title: "R Notebook"
output: 
  html_notebook:
     toc: TRUE
     toc_float: TRUE

---
This is lab4.

#Question 1: 

#Part a
```{r, echo=TRUE}
answer <- pnorm(20, mean = 32, sd = 7)
answer
curve(dnorm(x, mean = 32, sd =7), from = 0, to = 53)
x <- c(0,seq(0, 20,0.01),20)
y <- c(0, dnorm(seq(0,20,0.01), mean = 32, sd = 7),0)
polygon(x, y, col = "blue")
```

#Part b
```{r}
answer <- pnorm(35, mean = 32, sd =7, lower.tail = FALSE)
answer
curve(dnorm(x, mean = 32, sd =7), from = 0, to = 53)
xb <- c(35, seq(35, 53, 0.01), 53)
yb <- c(0, dnorm(seq(35,53,0.01), mean = 32, sd = 7), 0)
polygon(xb, yb, col = "purple")
```

#Part c
```{r}
curve(dnorm(x, mean = 32, sd = 7), from = 0, to =53)
xc <- c(20, seq(20,40,0.01),40)
yc <- c(0, dnorm(seq(20,40,0.01), mean = 32, sd = 7),0)
polygon(xc, yc, col = "gray")

a <- pnorm(20， mean = 32,sd = 7)
b <- pnorm(40, mean = 32, sd =7)
b - a 
```

#Question 2:
#Part a
```{r, echo=TRUE}
answer <- pexp(3,0.1)
answer
curve(dexp(x,0.1), from = 0, to = 70)
xc <- c(0, seq(0,3,1),3)
yc <- c(0, dexp(seq(0,3,1),0.1),0)
polygon(xc, yc, col = "pink")
```

#Part b
```{r}
answer <- pexp(20, 0.1, lower.tail = FALSE)
answer
curve(dexp(x, 0.1), from = 0, to = 50)
xc <- c(20, seq(20,50,1), 50)
yc <- c(0, dexp(seq(20,50,1), 0.1),0)
polygon(xc, yc, col = "yellow")
```

#Part c
```{r}
answer <- pexp(10,0.1) - pexp(5,0.1)
answer
curve(dexp(x,0.1), from = 0, to = 50)
xc <- c(5,seq(5,10,0.1), 10)
yc <- c(0, dexp(seq(5,10,0.1), 0.1), 0)
polygon(xc, yc, col = "green")
```

#Question 3:
#Part a
```{r}
library(raster)
ras1 <- raster(nrows=30, ncols=30,xmn=0,xmx=10,ymn=0,ymx=10)
ras1[] <- runif(ncell(ras1))
plot(ras1)
hist(ras1)
```

#Part b
```{r}
ras2 <- raster(nrows=30, ncols=30,xmn=0,xmx=10,ymn=0,ymx=10)
ras2[] <- rnorm(ncell(ras2))
plot(ras2)
hist(ras2)
```

#Part c
```{r}
ras <- raster(nrows=30, ncols=30,xmn=0,xmx=10,ymn=0,ymx=10)
ras3 <- ras1 + ras2
plot(ras3)
hist(ras3)
```

#Part d
```{r}
if(!require(rgdal))install.packages("rgdal")
library(rgdal)
cellStats(ras3,"mean")
ras3[ras3 > 0.5] <- 1
ras3[ras3 <= 0.5] <- 0
plot(ras3)
writeRaster(ras3, filename = "yanan.tif", overwrite = TRUE)
```

